export { registerDataWalletAavePortfolio } from './wallet-aave-data-portfolio'
export { registerDataAaveSupplyPool } from './aave-supply-pool'
export { registerDataAaveBorrowReserveAsset } from './aave-borrow-reserve-asset'
export { registerDataERC20Transfer } from './erc20-transfer'
export { registerDataERC20BalanceOf } from './erc20-balance-of'
export { registerDataAaveRepayDebt } from './aave-repay-debt'
export { registerDataAaveWithdrawAsset } from './aave-withdraw-asset'
